@url = tfgrid.workloads.reservation.gateway.proxy.1
workload_id = (I)
node_id = (S)
domain = (S)
destination = (S) # format 'ip:port'

@url = tfgrid.workloads.reservation.gateway.reserve_proxy.1
workload_id = (I)
node_id = (S)
domain = (S)
secret = (S) # the secret used by tcp router client. format must be 'threebotid:random_secret'

@url = tfgrid.workloads.reservation.gateway.subdomain.1
workload_id = (I)
node_id = (S)
domain = (S) # full domain. e.g: `user1.tfgw1.io`
ip = (LS) # list of target IP

@url = tfgrid.workloads.reservation.gateway.delegate.1
workload_id = (I)
node_id = (S)
domain = (S)
